config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  map.login 'login', :controller => 'authentication', :action => 'login'
  map.signup 'signup', :controller => 'users', :action => 'signup'
  map.about 'about', :controller => 'directory', :action => 'about'
  map.stats 'stats', :controller => 'directory', :action => 'stats'
  map.approved_users 'users/approved', :controller => 'users', :action => 'approved'
  map.unapproved_users 'users/unapproved', :controller => 'users', :action => 'unapproved'
  map.signup_thanks 'signup_thanks', :controller => 'users', :action => 'signup_thanks'
  map.browse_sectors 'browse/sectors', :controller => 'browse', :action => 'sector_index'
  map.by_sector 'browse/sector/:sector_id/country/:country_id', :controller => 'browse', :action => 'by_sector'
  map.narrow_sector_by_country 'browse/sector/:sector_id/country', :controller => 'browse', :action => 'narrow_sector_by_country'
  map.browse_countries 'browse/countries', :controller => 'browse', :action => 'country_index'
  map.by_country 'browse/country/:id', :controller => 'browse', :action => 'by_country'
  map.by_province 'browse/country/province/:id', :controller => 'browse', :action => 'by_province'
  map.analyze 'analyze', :controller => 'analyze', :action => 'index'
  map.save_image 'analyze/save_image', :controller => 'analyze', :action => 'save_image'
  map.contact 'contact', :controller => 'directory', :action => 'contact'
  
  
  map.resources :users

  map.resources :sectors

  map.resources :districts

  map.resources :countries

  map.resources :ngos
  
  map.resources :data_files

  map.resources :contacts

  map.resources :provinces

  

   map.root :controller => "search", :action => "index"

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/ngo.rb
class Ngo < ActiveRecord::Base
  
  belongs_to :country
  belongs_to :province
  belongs_to :district
  has_and_belongs_to_many :affiliations
  has_and_belongs_to_many :sectors
  has_and_belongs_to_many :contacts
  
  # this is used for the full text searching
  define_index do
    indexes :acronym
    indexes :name
    indexes country(:name), :as => :country_name
    indexes province(:name), :as => :province_name
    indexes district(:name), :as => :district_name
    indexes affiliations(:name), :as => :affiliation_name
    indexes sectors(:name), :as => :sector_name
    
    has country_id
    has province_id
    has district_id
    
    set_property :field_weights => {
      :name => 10,
      :sector_name    => 5,
      :country_name => 2,
      :province_name => 2,
      :district_name => 2
    }
    
  end
  
  def show_acronym
    self.acronym.nil? ? "---" : self.acronym
  end
  
  def show_name
    self.name.nil? ? "---" : self.name
  end
  
  def show_name_and_acronym
    name_and_acronym = ""
    name_and_acronym += self.name unless self.name.nil?
    name_and_acronym += " (#{self.acronym})" unless self.acronym.nil?
    name_and_acronym
  end
  
  def show_country
    if self.district_id.nil?
      "---"
    else
      if self.district.country_id.nil?
        "---"
      else
        self.district.show_country
      end
    end
  end
  
  def show_province
    self.province_id.nil? ? "---" : self.province.name
  end
  
  def show_district
    self.district_id.nil? ? "---" : self.district.name
  end

  def show_contact_address
    self.contact_address.nil? ? "---" : self.contact_address
  end
  
  def show_contact_phone
    self.contact_phone.nil? ? "---" : self.contact_phone
  end
  
  def show_contact_fax
    self.contact_fax.nil? ? "---" : self.contact_fax
  end
  
  def show_contact_email
    self.contact_email.nil? ? "---" : self.contact_email
  end

  def show_website
    self.website.nil? ? "---" : self.website
  end

  def show_sectors
    if self.sectors.nil? or self.sectors.size == 0
      "---"
    else
      names = ""
      self.sectors.each do |sector|
        names += sector.name
        unless sector == self.sectors.last
          names += ", "
        end
      end
      names
    end
  end
  
  def show_affiliations
    if self.affiliations.nil? or self.affiliations.size == 0
      "---"
    else
      names = ""
      self.affiliations.each do |affiliation|
        names += affiliation.name
        unless affiliation == self.affiliations.last
          names += ", "
        end
      end
      names
    end
  end
  
  def auto_update_value
    if self.auto_update
      "Yes"
    else
      "No"
    end
  end
  
  def has_contact?(contact)
    has_contact = false
    self.contacts.each do |ngo_contact|
      has_contact = true if ngo_contact.id == contact.id
    end
    has_contact
  end
  
  def find_contact?(name)
    contact_ids = Contact.find(:all, :conditions => ["name = ?", name]).map{|contact| contact.id }
    has_contact = false
    contact_ids.each do |contact_id|
      has_contact = true if self.contacts.map{|contact| contact.id}.include?(contact_id)
    end
    has_contact
  end
  
end

app/controllers/ngos_controller.rb
class NgosController < ApplicationController
  
  before_filter :authorize
  before_filter :admin_authorize, :except => ["view_details"]
  
  layout 'main_layout'
  
  # GET /ngos
  # GET /ngos.xml
  def index
    @ngos = Ngo.paginate(:per_page => 30, :page => params[:page], :order => "name")
    #@ngos = Ngo.find(:all, :order => "name")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ngos }
    end
  end

  # GET /ngos/1
  # GET /ngos/1.xml
  def show
    @ngo = Ngo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ngo }
    end
  end

  # GET /ngos/new
  # GET /ngos/new.xml
  def new
    @ngo = Ngo.new
    @countries = Country.find(:all, :order => "name")
    @provinces = Province.find(:all, :conditions => ["country_id = ?", @countries.first.id])
    @districts = District.find(:all, :conditions => ["country_id = ? and province_id = ?", @countries.first.id, @provinces.first.id])
    @sectors = Sector.find(:all, :order => "name")
    @affiliations = Affiliation.find(:all, :order => "name")

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ngo }
    end
  end

  # GET /ngos/1/edit
  def edit
    @ngo = Ngo.find(params[:id])
    @countries = Country.find(:all, :order => "name")
    @districts = District.find(:all, :conditions => ["country_id = ?",  @ngo.country_id])
    @provinces = Province.find(:all, :conditions => ["country_id = ?", @ngo.country_id])
    @sectors = Sector.find(:all, :order => "name")
    @affiliations = Affiliation.find(:all, :order => "name")
  end

  # POST /ngos
  # POST /ngos.xml
  def create
    @ngo = Ngo.new(params[:ngo])

    respond_to do |format|
      if @ngo.save
        flash[:notice] = 'Ngo was successfully created.'
        format.html { redirect_to(@ngo) }
        format.xml  { render :xml => @ngo, :status => :created, :location => @ngo }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ngo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ngos/1
  # PUT /ngos/1.xml
  def update
    @ngo = Ngo.find(params[:id])

    respond_to do |format|
      if @ngo.update_attributes(params[:ngo])
        flash[:notice] = 'Ngo was successfully updated.'
        format.html { redirect_to ngos_url }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ngo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ngos/1
  # DELETE /ngos/1.xml
  def destroy
    @ngo = Ngo.find(params[:id])
    @ngo.destroy

    respond_to do |format|
      format.html { redirect_to(ngos_url) }
      format.xml  { head :ok }
    end
  end
  
  
  # GET /ngos/1
  # GET /ngos/1.xml
  def view_details
    @ngo = Ngo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end
  
  
  def update_districts_provinces
    @provinces = Province.find(:all, :conditions => ["country_id = ?", params[:ngo_country_id].to_i], :order => "name")
    @districts = District.find(:all, :conditions => ["country_id = ? and province_id = ?", params[:ngo_country_id].to_i, @provinces.first.id], :order => "name")
    render :partial => "districts_provinces", :locals => {:districts => @districts, :provinces => @provinces}
  end
  
  def update_districts
    @districts = District.find(:all, :conditions => ["province_id = ?", params[:ngo_province_id].to_i], :order => "name")
    render :partial => "districts", :locals => {:districts => @districts}
  end
  
end

app/helpers/ngos_helper.rb
module NgosHelper
end

app/views/ngos/_districts.html.erb
<%= label_tag 'district_id', 'District' %>
<%= collection_select :ngo, :district_id, districts, :id, :name %>

<%= observe_field 'ngo_province_id',
		:url => { :action => :update_districts }, 
		:update => 'district_list',
		:with => "'ngo_province_id=' + encodeURIComponent(value)" %>

app/views/ngos/_districts_provinces.html.erb
<span id="districts_provinces">
	
<%= observe_field 'ngo_country_id',
		:url => { :action => :update_districts_provinces }, 
		:update => 'districts_provinces',
		:with => f %>

<li id="province_list">
	<%= render :partial => 'provinces', :locals => {:provinces => provinces }%>
	<%= check_box_tag :ngo_auto_update_province, ngo.auto_update_province, ngo.auto_update_province, {:name => "ngo[auto_update_province]"}  %>
</li>

<li id="district_list">
	<%= render :partial => 'districts', :locals => {:districts => districts }%>
	<%= check_box_tag :ngo_auto_update_district, ngo.auto_update_district, ngo.auto_update_district, {:name => "ngo[auto_update_district]"}  %>
</li>

</span>

app/views/ngos/_fields.html.erb
<ol>


<% if controller.action_name == "edit" %>
	<li>
	  <%= f.label :acronym %>
	  <%= f.text_field :acronym, {:disabled => true} %>
	</li>
	<li>
	  <%= f.label :name %>
	  <%= f.text_field :name, {:disabled => true} %>
	</li>
<% else %>
	<li>
	  <%= f.label :acronym %>
	  <%= f.text_field :acronym %>
	</li>
	<li>
	  <%= f.label :name %>
	  <%= f.text_field :name %>
	</li>
<% end %>	

	<li>
	  <%= f.label :country_id, 'Country' %>
		<%= collection_select :ngo, :country_id, @countries, :id, :name %>
		<%= f.check_box :auto_update_country %>
	</li>

	<%= render :partial => "districts_provinces", :locals => {:f => f, :districts => @districts, :provinces => @provinces, :ngo => @ngo }%>

	<li>
	  <%= f.label :sectors, 'Sector(s)' %>
		<%= collection_select :ngo, :sector_ids, @sectors, :id, :name, {}, :size => 7, :multiple => true %>
		<%= f.check_box :auto_update_sectors %>
	</li>
	<li>
	  <%= f.label :contact_address %>
	  <%= f.text_field :contact_address %>
		<%= f.check_box :auto_update_contact_address %>
	</li>
	<li>
	  <%= f.label :contact_phone %>
	  <%= f.text_field :contact_phone %>
		<%= f.check_box :auto_update_contact_phone %>
	</li>
	<li>
	  <%= f.label :contact_fax %>
	  <%= f.text_field :contact_fax %>
		<%= f.check_box :auto_update_contact_fax %>
	</li>
	<li>
	  <%= f.label :contact_email %>
	  <%= f.text_field :contact_email %>
		<%= f.check_box :auto_update_contact_email %>
	</li>
	<li>
	  <%= f.label :website %>
	  <%= f.text_field :website %>
		<%= f.check_box :auto_update_website %>
	</li>
	<li>
	  <%= f.label :affiliations, 'Affiliation' %>
		<%= collection_select :ngo, :affiliation_ids, @affiliations, :id, :name, {}, :size => 5, :multiple => true %>
		<%= f.check_box :auto_update_affiliation %>
	</li>

</ol>

app/views/ngos/_provinces.html.erb
<%= label_tag 'province_id', 'Province' %>
<%= collection_select :ngo, :province_id, provinces, :id, :name %>

app/views/ngos/edit.html.erb
<div id="mashera-form">

	<% form_for(@ngo) do |f| %>
	  <%= f.error_messages %>

		<div id="third-col-title">
			Auto-update?
		</div>


		<fieldset>

			<%= render :partial => 'fields', :locals => {:f => f } %>

	  	<div class="buttonHolder">
	    	<%= f.submit 'Update' %>
	  	</div>

		</fieldset>
		
	<% end %>

	
	<div id="page-links">
		<%= link_to 'Show', @ngo %> |
		<%= link_to 'Back', ngos_path %>
	</div>

</div>

app/views/ngos/index.html.erb
<div id="results">

	<table>
	
	  <tr>
	    <th width="50px">Acronym</th>
	    <th width="350px">Name</th>
	    <th>Country</th>
			<th>Province</th>
	    <th>District</th>
		 	<th>Sector(s)</th>
		  <th>Details</th>	
			<th>Edit</th>	
			<th>Destroy</th>	
	  </tr>

	<% @ngos.each do |ngo| %>
	  <tr class="<%= cycle('alt', '') %>">
	    <td width="50px"><%= ngo.show_acronym %></td>
	    <td width="350px"><%= ngo.show_name %></td>
	    <td><%= ngo.show_country %></td>
			<td><%= ngo.show_province %></td>
	    <td><%= ngo.show_district %></td>
		  <td width="350px"><%= ngo.show_sectors %></td>
	    <td><%= link_to 'Details', ngo %></td>
	    <td><%= link_to 'Edit', edit_ngo_path(ngo) %></td>
	    <td><%= link_to 'Destroy', ngo, :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	<% end %>
	</table>
<%= will_paginate %>

	<div id="page-links">
	<%= link_to '+ Add New NGO', new_ngo_path %>
	</div>
</div>

app/views/ngos/new.html.erb
<div id="mashera-form">

	<% form_for(@ngo) do |f| %>
	  <%= f.error_messages %>
	
		<div id="third-col-title">
			Auto-update?
		</div>

		<fieldset>

			<%= render :partial => 'fields', :locals => {:f => f} %>

	  	<div class="buttonHolder">
	    	<%= f.submit 'Create' %>
	  	</div>

		</fieldset>
		
	<% end %>


	<div id="page-links">
	<%= link_to 'Show', @ngo %> |
	<%= link_to 'Back', ngos_path %>
	</div>

</div>

app/views/ngos/show.html.erb
<div id="mashera-form">

	<fieldset>
		
		<ol>

		<li>
		  <label>Acronym:</label>
		  <%= @ngo.show_acronym %>
		</li>

		<li>
		  <label>Name:</label>
		  <%= @ngo.show_name %>
		</li>

		<li>
		  <label>Country:</label>
		  <%= @ngo.show_country %>
		</li>

		<li>
		  <label>District:</label>
		  <%= @ngo.show_district %>
		</li>

		<li>
		  <label>Sector:</label>
		  <%= @ngo.show_sectors %>
		</li>

		<li>
		  <label>Affiliation:</label>
		  <%= @ngo.show_affiliations %>
		</li>

		<li>
		  <label>Contact address:</label>
		  <%= @ngo.show_contact_address %>
		</li>

		<li>
		  <label>Contact phone:</label>
		  <%= @ngo.show_contact_phone %>
		</li>

		<li>
		  <label>Contact fax:</label>
		  <%= @ngo.show_contact_fax %>
		</li>

		<li>
		  <label>Contact email:</label>
		  <%= @ngo.show_contact_email %>
		</li>
		
		<li>
		  <label>Website:</label>
		  <%= @ngo.show_website %>
		</li>
		
		</ol>
		
	</fieldset>
		

	<div id="page-links">
	<%= link_to 'Edit', edit_ngo_path(@ngo) %> |
	<%= link_to 'Back', ngos_path %>
	</div>
	
</div>

app/views/ngos/view_details.html.erb
<div id="page-title">
	<h1><%= @ngo.name %>: Details</h1>
</div>

<div id="article-content">
	<fieldset>

		<ol>
			<li>
			  <label>Acronym:</label>
			  <%= @ngo.show_acronym %>
			</li>

			<li>
			  <label>Name:</label>
			  <%= @ngo.show_name %>
			</li>

			<li>
			  <label>Country:</label>
			  <%= @ngo.district.show_country %>
			</li>
		
			<li>
			  <label>Province:</label>
			  <%= @ngo.district.show_province %>
			</li>

			<li>
			  <label>District:</label>
			  <%= @ngo.show_district %>
			</li>

			<li>
			  <label>Sector(s):</label>
			  <%= @ngo.show_sectors %>
			</li>

			<li>
			  <label>Affiliation(s):</label>
			  <%= @ngo.show_affiliations %>
			</li>

			<li>
			  <label>Address:</label>
			  <%= @ngo.show_contact_address %>
			</li>

			<li>
			  <label>NGO Phone:</label>
			  <%= @ngo.show_contact_phone %>
			</li>

			<li>
			  <label>Fax:</label>
			  <%= @ngo.show_contact_fax %>
			</li>
		
			<li>
			  <label>NGO email:</label>
			  <%= mail_to @ngo.show_contact_email, nil, :replace_at => " AT " %>
			</li>
		
			<% @ngo.contacts.each do |contact| %>
			<li>
			  <label>Contact:</label>
				<%= contact.show_contact %>
			</li>
			<% end %>
		
			<li>
			  <label>Website:</label>
			  <%= @ngo.show_website %>
			</li>
		</ol>
			
</div>